### ISSUE TITLE
Listing of watches with 593 module

### ISSUE THREAD

**Issue by wryun** [joeycastillo/sensorwatch.net#3]
I just got my sensor watch boards (hooray!) and now need to purchase a watch for them (was reluctant to overinvest before boards arrived...).

Would you be open to a PR detailing what watches I think should work?

i.e. something like:

| Watch | Made in... | Current variants | Counterfeits (maybe) |
| --- | --- | --- | --- |
| F84W (? or module 587?) | Japan | ... | no |
| F91W | China | ... | yes |
| F98W | ? | ... | no |
| A158 | China | ... | yes |
| A159 | Japan | ... | yes |
| A163 | Thailand? | ... | ? |
| A164 | Thailand? | ... | ? |
| A171 | Thailand | ... | no |

(watches that look like they might have a 593 module, but don't: A168, A700)

**Comment by wryun** [comment]
Ah, just saw https://github.com/joeycastillo/Sensor-Watch/wiki/Compatible-Models

Is this the right place to update then, or should this info be promoted to the main website?

**Comment by joeycastillo** [comment]
Super open to this! and yes, absolutely think the web site is the right place for it. I need to deprecate all those old wiki pages and redirect folks to the relevant pages on the website.

**Comment by joeycastillo** [comment]
Looks good! Only question: have you tested all of these? If not I would propose adding one column for whether they've been tested by someone in the community and confirmed to be compatible. Between my testing and what I've seen from the community, we can check off the F-91W, F-91WM, F-91WS, F-91WC and A158.

**Comment by joeycastillo** [comment]
Addressed by #6.
